language: swift
podfile: DKPhotoGalleryDemo/Podfile

osx_image: xcode10
xcode_sdk: iphonesimulator11.3

before_install:
  - rvm use system
  - brew install ruby
  - sudo gem install cocoapods -v '1.5.0'
  - pod repo update

script:
- xcodebuild clean build test -workspace DKPhotoGalleryDemo/DKPhotoGalleryDemo.xcworkspace -scheme DKPhotoGalleryDemo -destination "platform=iOS Simulator,name=iPhone 7"